### PR TITLE
Update analysis_connection.go

### PR DESCRIPTION
**Pull request by Vericlongmore**
set scan limit num

### CODE REVIEW

**Comment by Vericlongmore** [comment]
examples/main.go

`	analysis.SetScanNum(3000)`

**Comment by hhxsv5** [comment]
Thanks.

**Comment by hhxsv5** [comment]
Please update the README example.

**Comment by Vericlongmore** [comment]
> Please update the README example.

ok，default value of 3000 is not set

**Comment by hhxsv5** [comment]
OK

**Pull request merged**
